dist: bionic
sudo: required
language:
  - cpp
compiler:
  - gcc
before_install:
  - sudo apt install -y libboost-dev
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-8
      - g++-8
      - libboost-dev
      - qt5-qmake
script:
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  - gcc -v && g++ -v && qmake --version
  - dpkg -s libboost-dev | grep 'Version'
  - mkdir build && cd build
  - qmake ..
  - make
