dist: bionic
sudo: required
language:
  - cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:mhier/libboost-latest
  - sudo apt update
  - sudo apt search libboost
  - sudo apt install -y libboost-all-dev
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-8
      - g++-8
      - boost1.70
      - qt5-qmake
script:
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  - gcc -v && g++ -v && qmake --version
  - dpkg -s libboost-dev | grep 'Version'
  - mkdir build && cd build
  - qmake ..
  - make
