dist: bionic
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - gcc-8
      - g++-8
      - libboost-dev
      - qt5-qmake
script:
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  - gcc -v && g++ -v && qmake --version
  - mkdir build && cd build
  - qmake ..
  - make
